### PR TITLE
Add basic auth to heroku app

### PR DESCRIPTION
**Pull request by barrucadu**
Copied from: https://github.com/alphagov/finder-frontend/blob/master/app.json

---

Visual regression results:
https://government-frontend-pr-1460.surge.sh/gallery.html

Component guide for this PR:
https://government-frontend-pr-1460.herokuapp.com/component-guide

### CODE REVIEW

**Comment by nickcolley** [comment]
Can we document the username and password clearly for developers?

**Comment by barrucadu** [comment]
It'll be the same username and password as all the other preview apps, though I don't know where that's documented.

**Comment by bevanloon** [comment]
The password is documented in a few places on our internal wiki.
It's possibly also somewhere in secrets?

**Comment by nickcolley** [comment]
Does this mean documentation such as component guides will be locked down?

http://government-frontend.herokuapp.com/component-guide

If possible it'd be good to have pages like this available to everyone as other people such as designers will need to reference them.

https://docs.publishing.service.gov.uk/manual/components.html#component-guides

**Comment by barrucadu** [comment]
Yes, everything will be locked down.   Maybe a robots.txt would be better

**Comment by nickcolley** [comment]
I think the username and password is a really good idea for the indexed pages, but I'm just wondering if we can do it in a way that doesnt close off the documentation that's also served by our frontend applications.

https://www.gov.uk/guidance/government-design-principles#make-things-open-it-makes-things-better

**Comment by sihugh** [comment]
How about this then: https://github.com/alphagov/government-frontend/pull/1461?

**Pull request closed without merging**
