### PR TITLE
Replaced Statistics logo with a higher quality version.

### PR DESCRIPTION
**Pull request by miaallers**
Amended Publisher-metadata-with-logo to have a 90px logo height. Replaced logo with a higher quality version.

Review app component guide:
https://government-frontend-pr-627.herokuapp.com/component-guide

Before:
www-origin integration publishing service gov uk-government-statistics-announcements-student-loans-in-wales-financial-year-2016-17

After:
localhost-3090-government-statistics-announcements-student-loans-in-wales-financial-year-2016-17 1

### CODE REVIEW

**Comment by nickcolley** [comment]
Example: https://government-frontend-pr-627.herokuapp.com/government/statistics/announcements/local-authority-collected-waste-management-annual-results--4

**Comment by nickcolley** [comment]
Is the png compressed? https://tinypng.com/ got some bytes off

**Comment by vanitabarrett** [comment]
Are we able to reduce the image size down further?

**Comment by miaallers** [comment]
png is compressed but will try compress further

**Comment by nickcolley** [comment]
Might be worth wacking the height on the img tag itself, if the CSS doesnt load it'll keep it's size and not be huuge.

https://github.com/alphagov/government-frontend/blob/220b386d729336b8c871d6ee29967f219317faf5/app/views/shared/_publisher_metadata_with_logo.html.erb#L11

**Comment by miaallers** [comment]
Couldn't get it any smaller, will look at putting the height into the image tag. Thanks!

**Comment by miaallers** [comment]
Updated pull request with Nicks comments — placed the height into the image tag and deleted the css. Thanks!

**Comment by nickcolley** [comment]
Nice 🚢

**Comment by fofr** [comment]
👏 :100:

**Pull request merged**
