### PR TITLE
Plug in real data for Service manual topic refs and breadcrumbs

### PR DESCRIPTION
**Pull request by tadast**
- If there is a topic associated to the guide, render its title above the guide
title. This replaces the hard-coded 'Topic'.
- Render breadcrumbs for SM Guides

See commit notes for more detailed descriptions

### CODE REVIEW

**Comment by tadast** [comment]
Actually this relies on https://github.com/alphagov/static/pull/716 to be merged first

**Comment by gemmaleigh** [comment]
LGTM :+1:

**Comment by gemmaleigh** [comment]
Hi @dsingleton, this is the first PR to remove duplicate styles in /components/.

Can you please confirm you're happy with these changes, so we can go ahead and rebase the remaining branches?

**Comment by tadast** [comment]
Your changes LGTM too Gemma, I'm going to merge.

**Comment by dsingleton** [comment]
:+1:

**Pull request merged**
