### PR TITLE
Add config and instructions for comparing examples with wraith

### PR DESCRIPTION
**Pull request by fofr**
Not all formats are live, and live content changes. Sometimes it’s preferable to compare examples on a branch against master.

* Create wraith config for testing diffs of examples
* Include instructions on how to generate diffs in readme

Example output:
https://fofr.github.io/government-frontend-wraith-tests/shots/gallery.html

Examples generated using this gist:
https://gist.github.com/fofr/765604f8ae27164736ac4a8c8e96ddeb

### CODE REVIEW

**Comment by nickcolley** [comment]
Nit: Should `config-examples` be `content-examples`?

**Comment by fofr** [comment]
@nickcolley All other configs begin with `config-`

**Comment by nickcolley** [comment]
Ah, sorry, stupid question then.

**Comment by fofr** [comment]
The example linked to here
https://fofr.github.io/government-frontend-wraith-tests/shots/gallery.html

Gives a couple of false positives. Running it a few times the false positives remain, but appear on different formats. I think it's something to do with the way phantom is handling broken images and how it spaces them, as there's no code differences between samples.

It's also odd that the webfont isn't rendering, but I recall this being an issue with all wraith tests.

**Pull request merged**
