### PR TITLE
Add fieldset component

### PR DESCRIPTION
**Pull request by nickcolley**
Review app component guide:
https://government-frontend-pr-561.herokuapp.com/component-guide/fieldset

https://trello.com/c/RRbQOeUK/243-create-a-fieldset-component-1

### CODE REVIEW

**Comment by emmabeynon** [comment]
LGTM, just wondering if we could squash these two commits, as the 2nd one is just overwriting the boilerplate generated in the 1s one?

**Comment by nickcolley** [comment]
Can do, I like doing commits for generation scripts, but not precious about it

**Comment by leenagupte** [comment]
@nickcolley The commit mentioned tests?

**Comment by nickcolley** [comment]
@leenagupte I was cleaning up some merge conflicts and I think nuked the tests for this.

Reopened here: https://github.com/alphagov/government-frontend/pull/563

**Pull request merged**
